# Generated by Django 6.0.3 on 2026-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer'), ('data_entry', 'Data Entry')], default='viewer', max_length=10),
        ),
    ]
